import type { Metadata } from 'next'

import './globals.css'
import Header from '@/components/common/Header'
import Footer from '@/components/common/Footer/Footer'
import "@/i18n"
import LangWrapper from '@/components/common/LangWrapper'
import getSettings from '@/lib/getSettings'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export async function generateMetadata(): Promise<Metadata> {
 
  // fetch data
  const res = await getSettings()
  const general = await res?.data?.general
 
  return {
    title: general.title,
    description: general.description
  }
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  const res = await getSettings()
  const general = await res?.data?.general
  console.log(general)
  return (
    <html>
      
        <LangWrapper>
        <Header/>
        <main className='flex-1'>
        {children}
        </main>
        <Footer/>
        </LangWrapper>
      
    </html>
  )
}
