import type { Metadata } from 'next'

import './globals.css'
import Header from '@/components/common/Header'
import Footer from '@/components/common/Footer/Footer'
import "@/i18n"
import LangWrapper from '@/components/common/LangWrapper'
import getSettings from '@/lib/getSettings'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export async function generateMetadata(): Promise<Metadata> {
 
  // fetch data
  const general = await getSettings('general')
 
  return {
    title: general.title,
    description: general.description
  }
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  const general = await getSettings('general')
  const socialMedia = await getSettings('socialMedia')


   console.log(socialMedia)
  return (
    <html>
      
        <LangWrapper>
        <Header general={general} />
        <main className='flex-1'>
        {children}
        </main>
        <Footer general={general} socialMedia={socialMedia} />
        </LangWrapper>
      
    </html>
  )
}
